apiVersion: v1
kind: Service
metadata:
  name: go-api-nodeport-service
  labels:
    app: go-api
spec:
  selector:
    app: go-api
  ports:
    - protocol: TCP
      port: 80      # Port exposed by the service
      targetPort: 8080 # Port on the container
      nodePort: 30000 # NodePort for external access
  type: NodePort # Type of service (ClusterIP, NodePort, LoadBalancer, etc.)