apiVersion: v1
kind: Service
metadata:
  name: go-api-service
  labels:
    app: go-api
spec:
  selector:
    app: go-api
  ports:
    - protocol: TCP
      name: http
      port: 80      # Port exposed by the service
      targetPort: 8080 # Port on the container
  type: ClusterIP # Type of service (ClusterIP, NodePort, LoadBalancer, etc.)