apiVersion: v1
kind: Service
metadata:
  name: hello-backend-service
  labels:
    app: hello-backend
spec:
  selector:
    app: hello-backend
  ports:
    - protocol: TCP
      name: http
      port: 80      # Port exposed by the service
      targetPort: http-api # Port on the container
  type: ClusterIP # Type of service (ClusterIP, NodePort, LoadBalancer, etc.)