apiVersion: v1
kind: Secret
metadata:
  name: hello-backend-credentials
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_HOST: postgres-headless-service.dev.svc.cluster.local
  POSTGRES_PORT: "5432"
  POSTGRES_NAME: labdatabase
  POSTGRES_SSL: disable
