apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
    - name: my-hostpath-container
      image: busybox:latest
      command: ["/bin/sh", "-c", "while true; do echo $(date -u) >> /data/test.txt; sleep 5; done"]
      volumeMounts:
        - name: hostpath-storage
          mountPath: /data # Path inside the container where the volume will be mounted
    
  volumes:
    - name: hostpath-storage
      persistentVolumeClaim:
        claimName: hostpath-pvc # Name of the PersistentVolumeClaim to use