apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless-service
spec:
  selector:
    app: mongodb-statefulset
  ports:
    - port: 27017 # target port for MongoDB as well
      name: mongodb
  clusterIP: None 