apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  mongod.conf: |
    # mongod.conf
    # Minimal configuration for MongoDB replica set.
    # Journaling is implicitly enabled in MongoDB 6.1+ (including 'latest' versions).
    # For full documentation, refer to the official MongoDB manual for your specific version.

    systemLog:
      destination: file
      logAppend: true
      path: /var/log/mongodb/mongod.log

    storage:
      dbPath: /data/db
      # The 'journal.enabled' option is removed as journaling is always enabled in MongoDB 6.1+.
      # Refer to MongoDB documentation for your exact 'mongo:latest' version if needed.

    processManagement:
      fork: false # mongod will run in foreground in container

    net:
      port: 27017
      bindIp: 0.0.0.0 # Binds to all network interfaces inside the container

    security:
      authorization: enabled
      keyFile: /etc/mongodb-keyfile/mongodb-keyfile

    replication:
      replSetName: rs0 # Important: The replica set name
