apiVersion: v1
kind: Service
metadata:
  name: mysql-headless-service
  labels:
    app: mysql-statefulset
spec:
  selector:
    app: mysql-statefulset 
  ports:
    - port: 3306
      name: mysql
  clusterIP: None 