apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
spec:
  serviceName: nginx-headless-service
  selector:
    matchLabels:
      app: nginx-statefulset
  replicas: 1
  minReadySeconds: 10 # Minimum time a pod should be ready before considering it available
  template:
    metadata:
      labels:
        app: nginx-statefulset
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html # Default serving directory for Nginx
    
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        storageClassName: custom-local-storage-class
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi # Requesting 1Gi of storage for the volume
        