apiVersion: v1
kind: Service
metadata:
  name: nginx-custom-service
  labels:
    app: nginx-custom
spec:
  selector:
    environment: nginx # Match the label used in the Deployment
  ports:
    - protocol: TCP
      name: http
      port: 80      
      targetPort: 80 
  type: ClusterIP 