apiVersion: apps/v1 
kind: Deployment   
metadata:
  name: nginx-configmap-deployment 
  labels:
    app: nginx-custom
  annotations:
    kubernetes.io/change-cause: "Deployment created with custom Nginx configuration"
spec:
  replicas: 1 
  selector:
    matchLabels: 
      app: nginx-custom 
      environment: nginx # Example label for environment
  template: 
    metadata:
      labels:
        app: nginx-custom # must match the selector above
        environment: nginx # Example label for environment
    spec:
      terminationGracePeriodSeconds: 60 # Grace period for pod termination
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80 
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf # Path inside the container where the contents of the configmap will be mounted
              subPath: nginx.conf #allows to mount specific file from the ConfigMap instead of the entire ConfigMap
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config # Name of the ConfigMap to use
