apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: observability # -Specified namespace since its a daemonset for montitoring
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      hostPID: true # Allows Node Exporter to access host PID namespace
      hostNetwork: true # Allows Node Exporter to use the host's network namespace
      volumes:
        - name: proc # This provides the Node Exporter access to process information on the host
          hostPath:
            path: /proc
        - name: sys # This gives Node Exporter access to kernel and system device information
          hostPath:
            path: /sys
        - name: dev # This allows Node Exporter to collect metrics like overall disk usage for the host.
          hostPath: 
            path: /dev
        - name: host-root
          hostPath: 
            path: / # Mounts the root filesystem of the host
      containers:
        - name: node-exporter
          image: prom/node-exporter:v1.8.0 
          ports:
            - containerPort: 9100 
              hostPort: 9100 # Exposes the port on the host
              name: metrics
          args:
            - --path.procfs=/host/proc 
            - --path.sysfs=/host/sys   
            - --path.rootfs=/host/root # Needed to access root filesystem metrics
            - --no-collector.wifi # Disable a specific collector if not needed
            - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+)($|/)
          resources:
            requests:
              memory: 100Mi
              cpu: 100m 
            limits:
              memory: 200Mi
              cpu: 200m 
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly: true
            - name: sys
              mountPath: /host/sys
              readOnly: true
            - name: dev
              mountPath: /host/dev
              readOnly: true
            - name: host-root
              mountPath: /host/root
              readOnly: true
      tolerations:
        - key: "node-role.kubernetes.io/master"
          effect: NoSchedule # Allows scheduling on master nodes if needed
        - key: "node-role.kubernetes.io/control-plane"
          effect: NoSchedule # Allows scheduling on control plane nodes if needed
        - key: CriticalAddonsOnly
          operator: Exists # Ensures the DaemonSet is scheduled on all nodes(even in aks,gks,eks) where critical addons are allowed
    
