apiVersion: v1
kind: Pod
metadata:
  name: pod-with-pvc
spec:
  containers:
    - name: pvc-container
      image: busybox:latest
      command: ["/bin/sh", "-c", "echo 'Hello from my-app-pod' > /mnt/data/test.txt && cat /mnt/data/test.txt && sleep infinity"]
      volumeMounts:
        - name: local-storage
          mountPath: /mnt/data # Path inside the container where the volume will be mounted
  volumes:
    - name: local-storage
      persistentVolumeClaim:
        claimName: custom-local-storage-class