apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: custom-local-storage-class
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Adjust the size as needed
  storageClassName: standard