apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-statefulset
  labels:
    app: redis
spec:
  serviceName: redis-headless-service
  selector:
    matchLabels:
      app: redis-statefulset
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: redis-statefulset
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
              name: redis
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          volumeMounts:
            - name: redis-data
              mountPath: /data # Default data directory for Redis
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        storageClassName: custom-local-storage-class
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi # Requesting 1Gi of storage for the volume