apiVersion: v1
kind: Service
metadata:
  name: redis-headless-service
  labels:
    app: redis
spec:
  selector:
    app: redis-statefulset
  ports:
    - name: redis
      port: 6379 
  clusterIP: None 
