# .github/workflows/hello-app-pipeline.yaml
name: Hello Backend Image Build, Scan, and Push (production)

on:
  push:
    branches:
      - main
    paths:
      - 'hello-backend/**' 
      - 'Dockerfile.hello' 
  workflow_dispatch:

jobs:
  build_scan_and_push_hello_app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # --- Build and Scan Hello App Image ---
      - name: Build Hello App Docker image (no push yet)
        uses: docker/build-push-action@v6
        with:
          context: . # Adjust context if your hello app code is in a subdirectory
          file: ./Dockerfile.hello # Adjust path to your hello app's Dockerfile
          tags: Portfolio_hello_app:latest
          outputs: type=docker
          push: false

      - name: Scan Hello App Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: portfolio_hello_app:latest
          format: 'table'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'
          ignore-unfixed: true

      - name: Push Hello App Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./hello-app # Adjust context
          file: ./hello-app/Dockerfile # Adjust path
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/portfolio_hello_app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/portfolio_hello_app:${{ github.run_number }}
          push: true